- name: Development Playbook
  hosts: local
  roles:
    - role: discord
      tags:
        - discord
        - application
    - role: docker
      become: true
      tags: docker
    - role: git
      tags:
        - git
    - role: intellij
      tags:
        - java
        - application
    - role: java
      tags:
        - java
    - role: python-packages
      tags: 
        - python-packages
    - role: vim
      tags:
        - vim
    - role: vscode
      tags:
        - vscode
        - application
    - role: vlc
      tags:
        - vlc
        - application

# - hosts: servers
#   tasks:
#   roles:
#     - servers