---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Discord
  become: true
  apt:
    deb: https://discord.com/api/download?platform=linux&format=deb